# Generated by Django 5.0.3 on 2024-03-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_hours', models.FloatField(default=0)),
                ('night_hours', models.FloatField(default=0)),
                ('holiday_hours', models.FloatField(blank=True, default=0, null=True)),
                ('vacation_hours', models.FloatField(blank=True, default=0, null=True)),
                ('sick_leave_hours', models.FloatField(blank=True, default=0, null=True)),
                ('night_shift_hours', models.FloatField(blank=True, default=0, null=True)),
                ('saturday_hours', models.FloatField(blank=True, default=0, null=True)),
                ('sunday_hours', models.FloatField(blank=True, default=0, null=True)),
                ('free_days', models.IntegerField(blank=True, default=0, null=True)),
                ('extra_hours', models.FloatField(blank=True, default=0, null=True)),
                ('turnus', models.CharField(blank=True, max_length=100, null=True)),
                ('vacation_days', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employees', models.ManyToManyField(related_name='schedule_entries', to='scheduler.employee')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.shifttype')),
            ],
            options={
                'unique_together': {('date', 'shift_type')},
            },
        ),
    ]
