# Generated by Django 5.0.3 on 2024-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_employeeshiftcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='extra_hours',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='free_days',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='night_shift_hours',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='turnus',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='vacation_days',
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_on_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
    ]
