# Generated by Django 5.0.3 on 2024-05-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_shifttype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='category',
            field=models.CharField(choices=[('1.smjena', '1.Smjena'), ('1.smjena priprema', '1.Smjena Priprema'), ('2.smjena', '2.Smjena'), ('2.smjena priprema', '2.Smjena Priprema'), ('ina 1.smjena', 'INA 1.Smjena'), ('ina 2.smjena', 'INA 2.Smjena'), ('janaf 1.smjena', 'JANAF 1.Smjena'), ('janaf 2.smjena', 'JANAF 2.Smjena'), ('godišnji odmor', 'Godišnji Odmor'), ('bolovanje', 'Bolovanje')], default='1.smjena', max_length=20),
        ),
    ]
