# Generated by Django 5.0.3 on 2024-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_shifttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='overtime_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
