# Generated by Django 5.0.3 on 2024-05-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_shifttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='schedule_entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='scheduler.scheduleentry'),
        ),
    ]
