# Generated by Django 5.0.3 on 2024-05-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_workday_schedule_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='schedule_entry',
        ),
    ]
