# Generated by Django 5.0.3 on 2024-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_excesshours'),
    ]

    operations = [
        migrations.AddField(
            model_name='excesshours',
            name='vacation_hours_used',
            field=models.IntegerField(default=0),
        ),
    ]
