# Generated by Django 5.0.6 on 2024-06-23 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_workday_continuation_workday_status_workday_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
