# Generated by Django 5.0.6 on 2024-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_alter_workday_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
