# Generated by Django 5.0.6 on 2024-06-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_alter_workday_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='continuation',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='version',
        ),
        migrations.AddField(
            model_name='shifttype',
            name='isNightShift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workday',
            name='shift_type',
            field=models.ForeignKey(default=1.5, on_delete=django.db.models.deletion.CASCADE, to='scheduler.shifttype'),
            preserve_default=False,
        ),
    ]
