# Generated by Django 5.0.6 on 2024-06-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_remove_workday_continuation_remove_workday_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='overtime_excess_fond',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_free_day',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_free_day_service',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_service',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='FreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_article_39', models.BooleanField(default=False)),
                ('is_byChoice', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee')),
            ],
        ),
    ]
