# Generated by Django 5.0.6 on 2024-09-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_sickleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
