# Generated by Django 5.0.6 on 2024-09-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_employee_role_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
