# Generated by Django 5.0.6 on 2024-10-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_workday_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
