# Generated by Django 5.0.6 on 2024-11-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_delete_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_vacation_hours',
            field=models.IntegerField(default=0),
        ),
    ]
